DROP TABLE IF EXISTS maps CASCADE;

CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  isPublic BOOLEAN NOT NULL DEFAULT FALSE
);
